### ISSUE TITLE
Dropping last character in font name

### ISSUE THREAD

**Issue by justinta** [daedreth/URXVTConfig#1]
When you change the font, it drops the last character of the font name, causing it not to load properly. I've noticed it with all the fonts I've tried. 

```
URxvt.font: xft:Anonymous Pr:pixelsize=12
```

**Comment by daedreth** [comment]
Unable to replicate, tried 10+ fonts, all seem to be saved correctly.
If someone else could attempt to replicate and report back, I'd be glad.

**Comment by justinta** [comment]
Interesting. I try it again a little later to get more information for you.

**Comment by Erisa** [comment]
Can't reporduce either, tried a bunch of fonts but they all work as expected.

**Comment by daedreth** [comment]
After extensive testing on multiple machines and different distributions, I was still unable to replicate said issue.

Closing, it's probably something on your end.
