### ISSUE TITLE
arch aur upgrade problem

### ISSUE THREAD

**Issue by innerout** [daedreth/URXVTConfig#10]
I have installed your package from aur and it is working perfectly.The only problem is that every time i run
yaourt -Syu --aur to update every package , urxvtconfig pops up with this
aur/urxvtconfig 1.0.r6.g3ef7024-1 -> 1.5.47d7f67-1 . That is happening for 3 days straight and i don't know if it is a problem of my laptop or something that you have misconfigured.
Keep up the good work!

**Comment by daedreth** [comment]
It's the AUR package that's broken.
I'll change it to use the latest release instead of the latest commit (as of now, same thing) and this won't be an issue anymore.

**Comment by daedreth** [comment]
@innerout it should be fixed now.
I don't know how to arch and I don't know how to AUR, I was luckily helped by someone who does, if any issue persists, comment here, I'll reopen it, if it works well, just close it again.
You *may* have to uninstall and reinstall urxvtconfig for it to actually work.

**Comment by daedreth** [comment]
Tested myself, works well enough. 
Closing

**Comment by innerout** [comment]
Everything works as it should now thanks.
