### ISSUE TITLE
Package for Void linux

### ISSUE THREAD

**Issue by ghost** [daedreth/URXVTConfig#12]
Hi @daedreth ! 

I created a package for Void linux, see [#9645](https://github.com/voidlinux/void-packages/pull/9645). 

Regards.

**Comment by daedreth** [comment]
I don't void, but the moment it's accepted and merged, give me instructions on how you would install the package on void and I'll add it the readme!

**Comment by ghost** [comment]
`xbps-install -S urxvtconfig`

😉

**Comment by daedreth** [comment]
done, thanks for the contribution

**Comment by daedreth** [comment]
@cr6git was the package actually accepted? I could not find it to add a link to the README

**Comment by ghost** [comment]
No, not yet.

**Comment by ghost** [comment]
Accepted and merged: [fa75d4c](https://github.com/voidlinux/void-packages/commit/fa75d4cb406455fd53aa9c79221c6ac60524dc1b).
