### ISSUE TITLE
32bit compatible

### ISSUE THREAD

**Issue by carks32** [daedreth/URXVTConfig#2]
So, yeah, I tried to build it and I'm running on a 32bit machine. Apparently you had it set it up only for 64bit on the qt4 libs. Is it possible to make it 32bit compatible?

**Comment by daedreth** [comment]
If you clone the project and open it in qtcreator you can select:
Projects>Build Settings>Build Steps>Qmake>Additional arguments

and add:
-spec linux-g++-32

To your build arguments.

By default QT doesn't play nice with deploying for 32bit on a 64bit machine, this workaround is questionable at best, and results in many issues and errors.

Will definitely look for a permanent solution soon.

**Comment by carks32** [comment]
Yeah, it works now, thanks. Have to manually move it to /usr/bin but whatever, thanks.
