### ISSUE TITLE
True transparency support

### ISSUE THREAD

**Issue by drgnomage** [daedreth/URXVTConfig#4]
Would it be possible to enable true transparency support by default?

Example:
URxvt*background:   [85]#232c31
URxvt*depth:        32

This is with the codeschool colour theme background.

**Comment by daedreth** [comment]
True transparency support is a feature I have wrongly assumed wasn't very popular.

Support for it will be added soon as at the very top of the list!

**Comment by drgnomage** [comment]
I'm not sure how popular it is but the fake transparency always felt very unpolished to me.

For feature requests like this, do you prefer an issue like this or possibly an open trello board?

**Comment by daedreth** [comment]
An issue is great, so I can tick 'em off after solving/adding.

**Comment by daedreth** [comment]
I added true transparency as an option, build from source to verify that it works.

Also, keep in mind that URXVT by default, if two transparency modes were to be enabled, will ALWAYS prefer the fake one, thus, make sure to disable it if you wish to use true transparency.

**Comment by drgnomage** [comment]
Functions as intended, thank you for this enhancement!

I will close the case.
